version: '0.0.1.{build}-alpha'

# enfoce CRLF fixing
init:
  - git config --global core.autocrlf true

image:
  - Visual Studio 2019
  - Ubuntu

platform: Any CPU
configuration: Release

for:
-
  matrix:
    except:
      - image: Ubuntu
  before_build:
    - nuget restore

skip_tags: true
build:
  project: ReleaseCleaner.sln

test:
  assemblies:
    only:
      - ReleaseCleanerTests.dll