version: '0.1.0.{build}-alpha'

# enfoce CRLF fixing
init:
  - git config --global core.autocrlf true

image:
  - Visual Studio 2022
  - Ubuntu

platform: Any CPU
configuration: Release

for:
-
  matrix:
    except:
      - image: Ubuntu
  before_build:
    - nuget restore

skip_tags: true
build:
  project: ReleaseCleaner.sln

test_script:
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=coverage.xml

on_success:
  - bash: curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import
  - bash: curl -Os https://uploader.codecov.io/latest/linux/codecov
  - bash: curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
  - bash: curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
  - bash: gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
  - bash: shasum -a 256 -c codecov.SHA256SUM
  - bash: chmod +x codecov
  - bash: ./codecov -f */coverage.xml