version: '0.0.1.{build}-alpha'

# enfoce CRLF fixing
init:
  - git config --global core.autocrlf true

image:
  - Visual Studio 2019
  - Ubuntu

platform: Any CPU
configuration: Release

for:
-
  matrix:
    except:
      - image: Ubuntu
  before_build:
    - nuget restore

skip_tags: true
build:
  project: ReleaseCleaner.sln

test:
  assemblies:
    only:
      - ReleaseCleanerTests.dll

# Push Notifications about build status to VBA Rubberducking
notifications:
  - provider: Webhook
    url: http://stats.zomis.net/GithubHookSEChatService/hooks/github/payload?roomId=14929
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: false