codecov:
  require_ci_to_pass: yes
  ci:
    - '!appveyor'

coverage:
  round: nearest
  precision: 2
  range: 60..90
  status:
    patch:
      default:
        only_pulls: true
        informational: true
        target: 70
        threshold: 5
    project:
      default:
        only_pulls: true
        informational: true
        target: 65
        threshold: 5
        base: auto

comment:
  layout: "flags, diff, files"
  behavior: once
